# Generated by Django 2.2.3 on 2019-07-13 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0002_auto_20190713_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='LecturerName',
            new_name='StudentName',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='StudentName',
            new_name='LecturerName',
        ),
    ]
