# Generated by Django 2.2.3 on 2019-07-13 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0003_auto_20190713_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='StudentName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
