# Generated by Django 2.2.3 on 2019-07-14 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Lecturer', '0007_auto_20190713_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.CharField(max_length=100)),
                ('AssignmentUpload', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('AssignmentTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lecturer.Assignment')),
                ('LecturerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Lecturer.Subject')),
            ],
        ),
    ]
