# Generated by Django 2.2.3 on 2019-07-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0008_viewassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='NoteUpload',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
