# Generated by Django 2.2.3 on 2019-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lecturer', '0009_auto_20190715_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='AssignmentUpload',
            field=models.FileField(upload_to='documents/%Y/%m/%d/'),
        ),
    ]
